// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/","file":"@/layouts/basicLayout.tsx","id":"1"},"2":{"path":"/","redirect":"/home","parentId":"1","id":"2"},"3":{"path":"/home","file":"@/pages/home/home.tsx","parentId":"1","id":"3"},"4":{"path":"/products","file":"@/pages/products/products.js","parentId":"1","id":"4"},"5":{"path":"/about","file":"@/pages/about/about.tsx","parentId":"1","id":"5"},"6":{"path":"/productDetail","file":"@/pages/productDetail/productDetail.tsx","id":"6"},"7":{"path":"/login","file":"@/pages/login/login.tsx","id":"7"}},
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__basicLayout" */'@/layouts/basicLayout.tsx')),
'2': React.lazy(() => import( './EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__home__home" */'@/pages/home/home.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__products__products" */'@/pages/products/products.js')),
'5': React.lazy(() => import(/* webpackChunkName: "p__about__about" */'@/pages/about/about.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__productDetail__productDetail" */'@/pages/productDetail/productDetail.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__login__login" */'@/pages/login/login.tsx')),
},
  };
}
